### ISSUE TITLE
Question: what is the rest.fasta?

### ISSUE THREAD

**Issue by Yutang-ETH** [lemene/PECAT#13]
Hi @lemene ,

Could you please explain to me what rest.fast is in the 3-assemble folder?

By the way, is it a good idea to use PECAT to assemble an inbred genome?

Thank you very much.

Best wishes,
Yutang

**Comment by lemene** [comment]
Hi, @Yutang-ETH 
For example, a bubble structure with three paths in the assembly graph. PECAT will generate three contigs, one in primary.fasta, one in alternate.fasta, and the other in rest.fasta. The contigs in rest.fasta are considered removed.
PECAT can assemble an inbred genome. Theoretically, unzip step can solve some repeats in inbred genomes.

**Comment by Yutang-ETH** [comment]
Hi @lemene,

Thank you very much for your detailed answer.

It is true that the phasing step could also separate repeats.

Thank you very much again.

Best wishes,
Yutang
