### ISSUE TITLE
Adapting ava-ont for plants

### ISSUE THREAD

**Issue by paracontias** [lemene/PECAT#14]
Hello,

I am making diploid drafts from R9 ONT reads of a 800Mb plant genome. 

I think Minimap does not collapse the haplotypes enough. The haploid draft is 1.2Gb and then phasing proceeds poorly.

I get a result of 854 Mb with Shasta using their plant-optimized settings. I think this draft may permit better phasing. I am wondering how to tune Minimap to have the same tolerances.

These are the Shasta settings optimized for plants:

[Align]
downsamplingFactor = 0.05
sameChannelReadAlignment.suppressDeltaThreshold = 30
maxSkip = 60
maxDrift = 20
maxTrim = 60
minAlignedMarkerCount = 200
minAlignedFraction = 0.3

I think 'maxSkip'  and 'minAlignedMarkerCount' are the most important. The defaults for human are 30 and 100. Shasta uses 10% of 15-mers selected at random which is about the same spacing as Minimap with -k 15 -w 10. 

I am not expert in minimizer space. Can you say how to flag minimap to achieve a similar state? Thank you.

**Comment by lemene** [comment]
Hi, 
What are the N50s of primary contigs and alternate contigs in the first/second round of assembly?  They are in the directory `3-assemble` and `5-assemble`.

**Comment by paracontias** [comment]
Hello,

For the first round, the primary is:

Main genome scaffold total:         	2064
Main genome contig total:           	2064
Main genome scaffold sequence total:	1196.646 MB
Main genome contig sequence total:  	1196.646 MB  	0.000% gap
Main genome scaffold N/L50:         	351/953.876 KB
**Main genome contig N/L50:           	351/953.876 KB**
Main genome scaffold N/L90:         	1224/298.901 KB
Main genome contig N/L90:           	1224/298.901 KB
Max scaffold length:                	7.881 MB
Max contig length:                  	7.881 MB
Number of scaffolds > 50 KB:        	1890
% main genome in scaffolds > 50 KB: 	99.62%

And the alternate is:

Main genome scaffold total:         	307
Main genome contig total:           	307
Main genome scaffold sequence total:	88.824 MB
Main genome contig sequence total:  	88.824 MB  	0.000% gap
Main genome scaffold N/L50:         	59/402.034 KB
**Main genome contig N/L50:           	59/402.034 KB**
Main genome scaffold N/L90:         	211/140.592 KB
Main genome contig N/L90:           	211/140.592 KB
Max scaffold length:                	1.593 MB
Max contig length:                  	1.593 MB
Number of scaffolds > 50 KB:        	294
% main genome in scaffolds > 50 KB: 	99.51%

For the second round, the primary is:

Main genome scaffold total:         	1869
Main genome contig total:           	1869
Main genome scaffold sequence total:	1145.416 MB
Main genome contig sequence total:  	1145.416 MB  	0.000% gap
**Main genome scaffold N/L50:         	301/1.092 MB**
Main genome contig N/L50:           	301/1.092 MB
Main genome scaffold N/L90:         	1045/325.683 KB
Main genome contig N/L90:           	1045/325.683 KB
Max scaffold length:                	8.101 MB
Max contig length:                  	8.101 MB
Number of scaffolds > 50 KB:        	1684
% main genome in scaffolds > 50 KB: 	99.56%

And the alternate is:

Main genome scaffold total:         	989
Main genome contig total:           	989
Main genome scaffold sequence total:	268.740 MB
Main genome contig sequence total:  	268.740 MB  	0.000% gap
**Main genome scaffold N/L50:         	132/528.158 KB**
Main genome contig N/L50:           	132/528.158 KB
Main genome scaffold N/L90:         	570/104.214 KB
Main genome contig N/L90:           	570/104.214 KB
Max scaffold length:                	5.037 MB
Max contig length:                  	5.037 MB
Number of scaffolds > 50 KB:        	867
% main genome in scaffolds > 50 KB: 	98.41%

These assemblies are of Cannabis which has a genome size of about 800 Mb and estimated heterozygosity of ~1%. 

Also I can show you this Merqury plot, because I have short reads of both F0s. 

![image](https://github.com/lemene/PECAT/assets/7071578/db72db35-05eb-4acd-b2fc-bfb404c37c91)

I am comparing PECAT to trio-binning and assembling separately with NECAT. With that method I got N50 of 2.0 and 1.6 Mb and genome size of ~750Mb. 

Thank you!

**Comment by lemene** [comment]
The total size of primary/alternate contigs in the first round are 1196/88 Mb. They are 1145/268Mb in the second round. Their expected values are 800/800 Mb. This result is poor, if its heterozygosity rate is high. Could you please provide the config file.

**Comment by paracontias** [comment]
Here you are. It is based on cfg_arab_ont, with the addition of '-f 0.005 -I 60G' in corr_rd2rd_options.

Also I have reduced lc and sc in phase_options because I have low coverage, about 35x. 

The purpose of this exercise is to quantify phasing precision and develop parameters to apply to new data which is 80x, but lacks parental kmers.

The heterozygosity is about 1%. 

[pecat_cfg.txt](https://github.com/lemene/PECAT/files/12620891/pecat_cfg.txt)

**Comment by lemene** [comment]
It's a bit strange to me that 1% is not very high but PECAT didn't collapse two haplotypes in the first round of assembly. Increasing the parameter `-g` of `minimap2` may be helpful. Using a lower threshold in the first round may be also helpful, such as:
`asm1_assemble_options=--max_trivial_length 10000 --min_identity  0.9`

In the second round, reducing parameter `diploid_rate` can move more contigs from primary.fasta to alternate.fasta, such as:
```
asm2_assemble_options=--max_trivial_length 10000 --contig_format dual,prialt --diploid_rate=0.1
```

**Comment by paracontias** [comment]
Hello,

I tried the changes mentioned, and also changed -g to first 6k and then
24k. The size of the primary and alt assemblies stays about the same, 1.2
Gb for primary and ~60 Mb for alternate. Only the N50 drops from about 1Mb
to 500kb. I also tried with -rmq and the same result.

If I concatenate the primary and alternate drafts (from default settings)
and then run purge_haplotigs I get a pretty nice result. So I think there
is good haplotype resolution but yes, not enough contigs being moved to
alternate.

I will close this for now and maybe ask more questions later.

Thank you!

**Comment by SanSanMX** [comment]
@COMInterop Hi, I'm having a similar result, did you concatenate the primary and alternate of 3-assemble?

 I would really appreciate your answer.

**Comment by COMInterop** [comment]
Hi Enrique,

No, I took the output of 6-polish, concatenated primary.fasta and alternate.fasta, and then ran purge_haplotigs to get curated.fasta. Then I take curated_haplotigs.fasta and run purge_haplotigs again to get the alternate assembly.

**Comment by SanSanMX** [comment]
@COMInterop Thank you very much for your valuable answer, I will try it. What numbers did you get after that? Well, if it is possible to know.

Thank you very much again.
