### ISSUE TITLE
Add pecat to bioconda

### ISSUE THREAD

**Issue by xiekunwhy** [lemene/PECAT#3]
Hi,

PECAT is not so easy to install, would you please add it to bioconda clouds?

Best,
Kun

**Comment by lemene** [comment]
Hi, @xiekunwhy 
We will add it to bioconda clouds in near future.  If you encounter installation failure, please let us know.  It may be a potential bug.

**Comment by xiekunwhy** [comment]
here is the error I have met today
g++ -std=c++11 -Wall -O3 -D_FILE_OFFSET_BITS=64 -I.  -I ../thirdparty/edlib/edlib/include -I ../thirdparty/ksw2 -c -MMD -MP -MF "../build/obj/./prog/fsa_kmer_bin.d" -MT "../build/obj/./prog/fsa_kmer_bin.o" -o "../build/obj/./prog/fsa_kmer_bin.o" "prog/fsa_kmer_bin.cpp"
g++ -std=c++11 -Wall -O3 -D_FILE_OFFSET_BITS=64 -I.  -I ../thirdparty/edlib/edlib/include -I ../thirdparty/ksw2 -c -MMD -MP -MF "../build/obj/./kmer/kmer_bin.d" -MT "../build/obj/./kmer/kmer_bin.o" -o "../build/obj/./kmer/kmer_bin.o" "kmer/kmer_bin.cpp"
ar -r ../build/bin/libfsa.a ../build/obj/./utils/argument_parser.o ../build/obj/./utils/logger.o ../build/obj/overlap.o ../build/obj/read_store.o ../build/obj/sequence.o ../build/obj/utility.o ../build/obj/file_io.o ../build/obj/seq_io.o ../build/obj/overlap_store.o ../build/obj/graph.o ../build/obj/assemble/overlap_assemble.o ../build/obj/simple_align.o ../build/obj/assemble/string_graph.o ../build/obj/assemble/read_variants.o ../build/obj/assemble/string_node.o ../build/obj/assemble/string_edge.o ../build/obj/assemble/asm_dataset.o ../build/obj/assemble/asm_options.o ../build/obj/assemble/stat_readinfo.o ../build/obj/../thirdparty/edlib/edlib/src/edlib.o ../build/obj/correct/aligner.o ../build/obj/./correct/dw.o ../build/obj/./correct/diff.o ../build/obj/./correct/align/edlib_aligner.o ../build/obj/./correct/align/ksw2_aligner.o ../build/obj/./utils/string_pool.o ../build/obj/./utils/pair_file.o ../build/obj/./utils/misc.o ../build/obj/./phase/phase_info.o ../build/obj/./phase/contig_phaser.o ../build/obj/assemble/simplify/simplifier.o ../build/obj/./assemble/simplify/spur.o ../build/obj/./assemble/simplify/bridge.o ../build/obj/./assemble/simplify/transitive.o ../build/obj/./assemble/simplify/cross.o ../build/obj/./assemble/simplify/low_quality.o ../build/obj/./assemble/simplify/unreliable.o ../build/obj/./assemble/simplify/loop.o ../build/obj/./assemble/simplify/bubble.o ../build/obj/./assemble/simplify/best.o ../build/obj/./assemble/simplify/semi_bubble.o ../build/obj/./assemble/simplify/repeat.o ../build/obj/./assemble/simplify/phase.o ../build/obj/./assemble/simplify/pbridge.o ../build/obj/./assemble/simplify/pspur.o ../build/obj/./correct/align/alignment_cache.o ../build/obj/./correct/align/tool_aligner.o ../build/obj/./correct/align/alignment.o ../build/obj/./correct/align/diff_aligner.o
ar: 正在创建 ../build/bin/libfsa.a
g++ ../build/obj/./prog/fsa_ol_assemble.o ../build/bin/libfsa.a -o ../build/bin/fsa_ol_assemble -pthread -lz ../build/bin/libksw2.a $
g++: 错误：$：No such file or directory
make[1]: *** [makefile:109：../build/bin/fsa_ol_assemble] 错误 1
make[1]: *** 正在等待未完成的任务....
kmer/kmer_bin.cpp: 在 lambda 函数中:
kmer/kmer_bin.cpp:63:35: 警告：unused variable ‘rate’ [-Wunused-variable]
             std::array<double, 2> rate { count[0]*1.0/ patkmers.Size(), count[1]*1.0/ matkmers.Size()};
                                   ^~~~
kmer/kmer_bin.cpp:56:22: 警告：unused variable ‘block_size’ [-Wunused-variable]
         const size_t block_size = 10000;
                      ^~~~~~~~~~
kmer/kmer_bin.cpp: 在成员函数‘size_t fsa::KmerBin::CountLines(const string&)’中:
kmer/kmer_bin.cpp:235:1: 警告：在有返回值的函数中未发现 return 语句 [-Wreturn-type]
 }
 ^
make[1]: 离开目录“/home/kxie/pipeline/Assemble/bin/apps/PECAT/src”
make: *** [makefile:15：src] 错误 2

错误 means error

**Comment by lemene** [comment]
Hi, 
There is a bug in `src/makefile` (https://github.com/lemene/PECAT/issues/2). I have fixed the bug.

**Comment by lemene** [comment]
`pecat` is avaliable from bioconda.
