### ISSUE TITLE
processing stage checking

### ISSUE THREAD

**Issue by chklopp** [lemene/PECAT#32]
I've assembled a genome with pecat "assemble" and it worked well but then I wanted to polish and phase it and after modifying the configuration file and rerunning pecat it started from the beginning. Could you modify pecat in ordered to take into account existing results and not restart from the beginning if not explicitly asked for?

**Comment by lemene** [comment]
Hi @chklopp 
PECAT can resume running from the interrupted position unless the previous file has been modified. This running logic is similar to a makefile.  However, PECAT ignores modifications of the configuration file. It is very likely that the input file has changed.

**Comment by chklopp** [comment]
Thank you @lemene for this answer.
