### ISSUE TITLE
Polish with short reads illumina

### ISSUE THREAD

**Issue by Karenmagh** [lemene/PECAT#37]
Hello, I have a question, is possible polish the primary/alternate and haplo1/haplo2 with illumina reads?

Thanks so much.

**Comment by lemene** [comment]
The `primary.fasta` and `alternate.fasta` files can be polished using Illumina data. It's best to concatenate them into a single file and polish them together. This method also applies to `haplotype_1.fasta` and `haplotype_2.fasta`.

**Comment by Karenmagh** [comment]
Do you recommend any subsequent method for re-separation? I am considering using Hapo-G (https://github.com/institut-de-genomique/HAPO-G) for polishing.

I would greatly appreciate your response @lemene

**Comment by lemene** [comment]
The contig names are different between `primary.fasta` and `alternate.fasta`. After polishing, the contigs can be separated by their names.  I have used Pilon but not Hapo-G, so I can't give useful advice on Hapo-G.

**Comment by Karenmagh** [comment]
Thanks so much @lemene  , you can close this issue.
