### ISSUE TITLE
zlib.h: No such file or directory

### ISSUE THREAD

**Issue by Yutang-ETH** [lemene/PECAT#6]
Hi @lemene,

First of all, thank you very much for providing PECAT.

I got one issue while I am installing PECAT on our local machine. I am installing it in a conda environment where I have perl, racon and minimap2 installed. I got the error saying zlib.sh: No such file or directory.

What I did is following:
git clone --recursive https://github.com/lemene/PECAT.git
cd PECAT
make

gcc version is /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper

And the message I got from make is follwoing:

(pecat) -bash-4.2$ make
cd ./thirdparty && make -j && cd -
make[1]: Entering directory `/scratch/yutang/PECAT/thirdparty'
tar -xzf pigz/pigz-2.4.tar.gz -C ../build/bin/.. || exit 255
echo  ../build/bin/Plgd/Task.pm  ../build/bin/Plgd/Utils.pm  ../build/bin/Plgd/Pipeline.pm  ../build/bin/Plgd/Config.pm  ../build/bin/Plgd/Grid.pm  ../build/bin/Plgd/Logger.pm  ../build/bin/Plgd/Job.pm  ../build/bin/Plgd/Grid/Sge.pm  ../build/bin/Plgd/Grid/Slurm.pm  ../build/bin/Plgd/Grid/Pbs.pm  ../build/bin/Plgd/Grid/Local.pm  ../build/bin/Plgd/Grid/Lsf.pm  ../build/bin/Plgd/Job/Function.pm  ../build/bin/Plgd/Job/Serial.pm  ../build/bin/Plgd/Job/Script.pm  ../build/bin/Plgd/Job/Parallel.pm
../build/bin/Plgd/Task.pm ../build/bin/Plgd/Utils.pm ../build/bin/Plgd/Pipeline.pm ../build/bin/Plgd/Config.pm ../build/bin/Plgd/Grid.pm ../build/bin/Plgd/Logger.pm ../build/bin/Plgd/Job.pm ../build/bin/Plgd/Grid/Sge.pm ../build/bin/Plgd/Grid/Slurm.pm ../build/bin/Plgd/Grid/Pbs.pm ../build/bin/Plgd/Grid/Local.pm ../build/bin/Plgd/Grid/Lsf.pm ../build/bin/Plgd/Job/Function.pm ../build/bin/Plgd/Job/Serial.pm ../build/bin/Plgd/Job/Script.pm ../build/bin/Plgd/Job/Parallel.pm
cd ksw2 && make
make[2]: Entering directory `/scratch/yutang/PECAT/thirdparty/ksw2'
gcc -c -g -Wall -Wextra -Wc++-compat -O2 -march=native -DHAVE_KALLOC -I. cli.c -o cli.o
cli.c:4:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make[2]: *** [cli.o] Error 1
make[2]: Leaving directory `/scratch/yutang/PECAT/thirdparty/ksw2'
make[1]: *** [ksw2/libksw2.a] Error 2
make[1]: *** Waiting for unfinished jobs....
cd ../build/bin/../pigz-2.4 && make
make[2]: Entering directory `/scratch/yutang/PECAT/build/pigz-2.4'
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas   -c -o pigz.o pigz.c
pigz.c:390:70: fatal error: zlib.h: No such file or directory
 #include "zlib.h"       // deflateInit2(), deflateReset(), deflate(),
                                                                      ^
compilation terminated.
make[2]: *** [pigz.o] Error 1
make[2]: Leaving directory `/scratch/yutang/PECAT/build/pigz-2.4'
make[1]: *** [../build/bin/../pigz-2.4/pigz] Error 2
make[1]: Leaving directory `/scratch/yutang/PECAT/thirdparty'
make: *** [thirdparty] Error 2

Could you please help? Thank you very much.

Best wishes,
Yutang

**Comment by lemene** [comment]
Hi, Yutang
`zlib-devel` may need to be install.
`conda install zlib-devel`

**Comment by Yutang-ETH** [comment]
Hi @lemene ,

Thank you very much for your reply. Unfortunately I found zlib-devel is not available via conda. Am I right? I also tried to install zlib by conda yesterday, but it didn't help. I will keep googling and get back to you if I find any reasonable solutions. If nothing works, I will turn to our IT guys for help.

Please see below the error from conda.

Best wishes,
Yutang

(pecat) -bash-4.2$ conda install zlib-devel
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - zlib-devel

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by lemene** [comment]
hi, @Yutang-ETH 
I remember wrong. It seems that there is no zlib-devel in conda.
You should install the development support files for zlib as follows.
`sudo apt-get install libz-dev`
or
`sudo apt-get install zlib1g-dev`

**Comment by Yutang-ETH** [comment]
Thank you very much @lemene  for your help.

I think I will have to contact our IT guys for help as I don't have the superuser permission.

In addition, look forward to the conda version.

Best wishes,
Yutang
