### ISSUE TITLE
A new error

### ISSUE THREAD

**Issue by leeun67** [lemene/PECAT#7]
Hi，when i  run the PECAT in the final unzip step,i got an error as follows,
Could you give me some suggestions?

“Run script /home/data3/pe/gg/scripts/pol_filter.sh
-x asm202023-03-01 18:57:39 [Info] Sumbit command: /home/data3/pe/gg/scripts/pol_filter.sh 2>&1 | tee /home/data3/pe/gg/scripts/pol_filter.sh.log
Plgd script start: 2023-03-01 18:57:39
/usr/bin/env: “python3\r”: 没有那个文件或目录
Plgd script end: 2023-03-01 18:57:39
2023-03-01 18:57:44 [Error] Failed to run filter overlaps in which the reads are different haplotypee”

**Comment by lemene** [comment]
Hi, @leeun67 
I guess the file `build/bin/fxtool.py` is in windows text file format and the lines end with `\r\n`. It would help if you converted it to UNIX text file format.

**Comment by leeun67** [comment]
> Hi, @leeun67 I guess the file `build/bin/fxtool.py` is in windows text file format and the lines end with `\r\n`. It would help if you converted it to UNIX text file format.

Thanks, i  solution the problem with your help.
